### ISSUE TITLE
Brand theming on Swyxkit

### ISSUE THREAD

**Issue by sw-yx** [sw-yx/swyxkit#15]
today i also implemented some nice brand color nuances to swyxkit

## highlighting/selection

<details>
<summary>

you can style the `::selection` pseudoelement and make it work in dark mode:

```css
  ::selection { background-color: var(--brand-accent); }
  .dark ::selection { color: #1d1d1d; }
```

</summary>

![image](https://user-images.githubusercontent.com/6764957/149643498-7ede2c54-5989-40e7-a9bd-166341b20a7b.png)

![image](https://user-images.githubusercontent.com/6764957/149643484-a2ce595e-9c87-4a32-b4fb-dab68729cfcf.png)

</details>

<details>

## Nav items

<summary>
i also put the brand color on to the nav items
</summary>

![image](https://user-images.githubusercontent.com/6764957/149643529-2cdd51b7-7abb-4cef-a18c-ca8b7dc1fbc3.png)
![image](https://user-images.githubusercontent.com/6764957/149643543-fa3feb93-5708-4b52-9792-7054f8f665c9.png)

</details>

## details/summary

```css
  /* https://css-tricks.com/two-issues-styling-the-details-element-and-how-to-solve-them/ */
  details {
    border: 2px solid var(--brand-accent);
    padding: 0.5rem 1rem;
  }
  details > summary { 
    cursor: pointer;
  }
  
  details > summary > *:first-child {
    display: inline;
  }
  
```

## landing page

and a lilttle pizazz on the index page

![image](https://user-images.githubusercontent.com/6764957/149643566-2c8d03b8-6572-46ab-9e68-0b8a3d6013d4.png)
